DATALOADER:
  TRAIN:
    BATCH_SIZE: 32
    NUM_INSTANCES: 4
    SAMPLER: "RandomIdentitySampler"
  TEST:
    BATCH_SIZE: 32
  NUM_WORKERS: 2

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.002
  MAX_EPOCH: 200
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 5

MODEL:
  NAME: CLIPZeroShot
  METRIC_LOSS_TYPE: "triplet"
  NO_MARGIN: False
  IF_LABELSMOOTH: "on"
  CLIPZeroShot:
    # BACKBONE: "RN50"
    BACKBONE: "ViT-B/32"