DATALOADER:
  TRAIN:
    BATCH_SIZE: 32
    SAMPLER: "RandomSampler"
  TEST:
    BATCH_SIZE: 64
    SAMPLER: "SequentialSampler"
  NUM_WORKERS: 8

DATASET:
  ROOT_DIR: "/path/to/your/datasets"
  NAME: "MultiReID"
  SOURCE_DOMAINS: ["tiger", "stoat"]  # Training datasets (domain_label 0, 1)
  TARGET_DOMAINS: ["market1501"]      # Test datasets (domain_label 2)

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.001
  MAX_EPOCH: 50
  LR_SCHEDULER: "Cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 5

MODEL:
  NAME: LGDS  # or BOLD, CLIPAdapter, etc.
  LGDS:
    BACKBONE: "ViT-B/32"

