DATALOADER:
  TRAIN:
    BATCH_SIZE: 32
    NUM_INSTANCES: 4
    SAMPLER: "RandomIdentitySampler"
  TEST:
    BATCH_SIZE: 64
  NUM_WORKERS: 8

INPUT:
  SIZE: (384, 384)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

OPTIM:
  NAME: "sgd"
  LR: 0.002
  MAX_EPOCH: 200
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 5

MODEL:
  NAME: SIGLIPZeroShot
  METRIC_LOSS_TYPE: "triplet"
  NO_MARGIN: False
  IF_LABELSMOOTH: "on"
  SIGLIPZeroShot:
    # BACKBONE: "RN50"
    CKPT: "google/siglip-so400m-patch14-384"